name: Auto Label Issues and PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - name: Apply labels to issues and PRs
        uses: actions-ecosystem/action-add-labels@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'bug,question,help needed'
